export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="facebook-domain-verification" content="zsuievznxnus9u8sdp7xhm7zb00xrh" />
      </head>
      <body>{children}</body>
    </html>
  )
}
