/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    staticpages: Staticpage;
    horecabenefits: Horecabenefit;
    domesticadvantages: Domesticadvantage;
    domesticconditions: Domesticcondition;
    domesticfaqs: Domesticfaq;
    domesticsteps: Domesticstep;
    voicebcalls: Voicebcall;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    staticpages: StaticpagesSelect<false> | StaticpagesSelect<true>;
    horecabenefits: HorecabenefitsSelect<false> | HorecabenefitsSelect<true>;
    domesticadvantages: DomesticadvantagesSelect<false> | DomesticadvantagesSelect<true>;
    domesticconditions: DomesticconditionsSelect<false> | DomesticconditionsSelect<true>;
    domesticfaqs: DomesticfaqsSelect<false> | DomesticfaqsSelect<true>;
    domesticsteps: DomesticstepsSelect<false> | DomesticstepsSelect<true>;
    voicebcalls: VoicebcallsSelect<false> | VoicebcallsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    domesticapage: Domesticapage;
    horecapage: Horecapage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    domesticapage: DomesticapageSelect<false> | DomesticapageSelect<true>;
    horecapage: HorecapageSelect<false> | HorecapageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staticpages".
 */
export interface Staticpage {
  id: number;
  title: string;
  /**
   * The URL path (e.g., "privacy-policy" or "cookies")
   */
  slug: string;
  backgroundImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "horecabenefits".
 */
export interface Horecabenefit {
  id: number;
  title: string;
  backgroundImage: number | Media;
  content: string;
  color: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domesticadvantages".
 */
export interface Domesticadvantage {
  id: number;
  title: string;
  backgroundImage: number | Media;
  content: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domesticconditions".
 */
export interface Domesticcondition {
  id: number;
  title: string;
  backgroundImage: number | Media;
  content: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domesticfaqs".
 */
export interface Domesticfaq {
  id: number;
  question: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domesticsteps".
 */
export interface Domesticstep {
  id: number;
  stepNumber: number;
  backgroundImage: number | Media;
  header: string;
  content: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "voicebcalls".
 */
export interface Voicebcall {
  id: number;
  channel: string;
  phone: string;
  result: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'staticpages';
        value: number | Staticpage;
      } | null)
    | ({
        relationTo: 'horecabenefits';
        value: number | Horecabenefit;
      } | null)
    | ({
        relationTo: 'domesticadvantages';
        value: number | Domesticadvantage;
      } | null)
    | ({
        relationTo: 'domesticconditions';
        value: number | Domesticcondition;
      } | null)
    | ({
        relationTo: 'domesticfaqs';
        value: number | Domesticfaq;
      } | null)
    | ({
        relationTo: 'domesticsteps';
        value: number | Domesticstep;
      } | null)
    | ({
        relationTo: 'voicebcalls';
        value: number | Voicebcall;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staticpages_select".
 */
export interface StaticpagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  backgroundImage?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "horecabenefits_select".
 */
export interface HorecabenefitsSelect<T extends boolean = true> {
  title?: T;
  backgroundImage?: T;
  content?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domesticadvantages_select".
 */
export interface DomesticadvantagesSelect<T extends boolean = true> {
  title?: T;
  backgroundImage?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domesticconditions_select".
 */
export interface DomesticconditionsSelect<T extends boolean = true> {
  title?: T;
  backgroundImage?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domesticfaqs_select".
 */
export interface DomesticfaqsSelect<T extends boolean = true> {
  question?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domesticsteps_select".
 */
export interface DomesticstepsSelect<T extends boolean = true> {
  stepNumber?: T;
  backgroundImage?: T;
  header?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "voicebcalls_select".
 */
export interface VoicebcallsSelect<T extends boolean = true> {
  channel?: T;
  phone?: T;
  result?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domesticapage".
 */
export interface Domesticapage {
  id: number;
  layout?: (HeroBlock | AdvantagesBlock | ConditionsBlock | FaqBlock | StepsBlock | SubfooterBlock)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  mainHeader?: string | null;
  subHeader?: string | null;
  facebooknumber?: string | null;
  googlenumber?: string | null;
  backgroundImage: number | Media;
  leftBoxText?: string | null;
  rightBoxFirstText?: string | null;
  rightBoxSecondText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AdvantagesBlock".
 */
export interface AdvantagesBlock {
  title: string;
  advantages?: (number | Domesticadvantage)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'advantages';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ConditionsBlock".
 */
export interface ConditionsBlock {
  domesticconditions?: (number | Domesticcondition)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'conditions';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  domesticfaqs?: (number | Domesticfaq)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock".
 */
export interface StepsBlock {
  title: string;
  domesticsteps?: (number | Domesticstep)[] | null;
  buttonText: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'steps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SubfooterBlock".
 */
export interface SubfooterBlock {
  mainHeader?: string | null;
  firstParagraph: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  secondParagraph: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  endText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'subfooter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "horecapage".
 */
export interface Horecapage {
  id: number;
  layout?: (HeroBlock | BenefitsBlock | SubfooterBlock)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBlock".
 */
export interface BenefitsBlock {
  mainHeader?: string | null;
  horecaBenefits?: (number | Horecabenefit)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'benefits';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  gtmId?: string | null;
  googleVerificationId?: string | null;
  cookiebotId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domesticapage_select".
 */
export interface DomesticapageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        advantages?: T | AdvantagesBlockSelect<T>;
        conditions?: T | ConditionsBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        steps?: T | StepsBlockSelect<T>;
        subfooter?: T | SubfooterBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  mainHeader?: T;
  subHeader?: T;
  facebooknumber?: T;
  googlenumber?: T;
  backgroundImage?: T;
  leftBoxText?: T;
  rightBoxFirstText?: T;
  rightBoxSecondText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AdvantagesBlock_select".
 */
export interface AdvantagesBlockSelect<T extends boolean = true> {
  title?: T;
  advantages?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ConditionsBlock_select".
 */
export interface ConditionsBlockSelect<T extends boolean = true> {
  domesticconditions?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  domesticfaqs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock_select".
 */
export interface StepsBlockSelect<T extends boolean = true> {
  title?: T;
  domesticsteps?: T;
  buttonText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SubfooterBlock_select".
 */
export interface SubfooterBlockSelect<T extends boolean = true> {
  mainHeader?: T;
  firstParagraph?: T;
  secondParagraph?: T;
  endText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "horecapage_select".
 */
export interface HorecapageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        benefits?: T | BenefitsBlockSelect<T>;
        subfooter?: T | SubfooterBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBlock_select".
 */
export interface BenefitsBlockSelect<T extends boolean = true> {
  mainHeader?: T;
  horecaBenefits?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  gtmId?: T;
  googleVerificationId?: T;
  cookiebotId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}